# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - nightly
notifications:
  email: false
script:
  - julia -e 'using Pkg; pkg"dev https://github.com/stevengj/GeometryPrimitives.jl"; pkg"dev https://github.com/wsshin/StaggeredGridCalculus.jl"; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - codecov
