# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - nightly
notifications:
  email: false
script:
  - julia --color=yes -e 'using Pkg; Pkg.build()''
  - julia --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
after_success:
  - codecov
